// mockPatientData.js
const mockPatientData = {
    1: {
        id: 1,
        fullName: 'John Doe',
        hospitalNumber: '12345',
        gender: 'male',
        dateOfAdmission: '2024-07-20',
        address: '123 Main St',
        nextOfKin: 'Jane Doe',
        weight: 70,
        height: 175,
        medicalHistory: 'No major issues',
        presentingComplaints: 'Fever, cough',
        systemicReview: 'Normal',
        familyHistory: 'Hypertension',
        additionalRelevantHistory: '',
        bookedANC: 'Yes',
        gestationalAgeBooking: '12 weeks',
        normalDelivery: 'No',
        specificDeliveryDetails: 'C-section',
        neonatalProblems: 'None',
        congenitalAnomalies: 'None',
        childhoodVaccines: 'Complete',
        otherVaccines: 'Flu',
        nutritionalAssessment: 'Good',
        developmentalAssessment: 'Normal',
        regressionMilestones: 'None',
        childInSchool: 'Yes',
        className: 'Grade 5',
        performanceSatisfactory: 'Yes',
        pastIllnessesDrugHistory: 'Asthma',
        interventionsCurrentIllness: 'Antibiotics',
        patentMedicineVendors: 'No',
        traditionalHealer: 'No',
        hospitalTreatment: 'Admitted',
        previousTreatmentDetails: 'Inhaler',
        radiationExposure: 'None',
        otherExposures: 'Smoke',
        headCircumference: 55,
        spo2: 98,
        temperature: 37.5,
        heartRate: 80,
        respiratoryRate: 18,
        bloodPressure: '120/80',
        enlargedLymphNodes: 'No',
        status: 'admitted',
    },
    2: {
        id: 2,
        fullName: 'Jane Smith',
        hospitalNumber: '67890',
        gender: 'female',
        dateOfAdmission: '2024-07-15',
        address: '456 Oak Ave',
        nextOfKin: 'Peter Smith',
        weight: 60,
        height: 160,
        medicalHistory: 'Diabetes',
        presentingComplaints: 'Fatigue, thirst',
        systemicReview: 'Normal',
        familyHistory: 'Diabetes',
        additionalRelevantHistory: '',
        bookedANC: 'Yes',
        gestationalAgeBooking: '10 weeks',
        normalDelivery: 'Yes',
        specificDeliveryDetails: 'Normal',
        neonatalProblems: 'None',
        congenitalAnomalies: 'None',
        childhoodVaccines: 'Complete',
        otherVaccines: 'Flu',
        nutritionalAssessment: 'Needs improvement',
        developmentalAssessment: 'Normal',
        regressionMilestones: 'None',
        childInSchool: 'Yes',
        className: 'Grade 3',
        performanceSatisfactory: 'Yes',
        pastIllnessesDrugHistory: 'Metformin',
        interventionsCurrentIllness: 'Insulin',
        patentMedicineVendors: 'No',
        traditionalHealer: 'No',
        hospitalTreatment: 'Admitted',
        previousTreatmentDetails: 'Insulin',
        radiationExposure: 'None',
        otherExposures: 'None',
        headCircumference: 54,
        spo2: 99,
        temperature: 37.2,
        heartRate: 75,
        respiratoryRate: 16,
        bloodPressure: '110/70',
        enlargedLymphNodes: 'No',
        status: 'admitted',
    },
    3: {
        id: 3,
        fullName: 'Alice Johnson',
        hospitalNumber: '24680',
        gender: 'female',
        dateOfAdmission: '2024-07-22',
        address: '789 Pine Ln',
        nextOfKin: 'Bob Johnson',
        weight: 80,
        height: 180,
        medicalHistory: 'Hypertension',
        presentingComplaints: 'Chest pain, shortness of breath',
        systemicReview: 'Cardiovascular issues',
        familyHistory: 'Heart disease',
        additionalRelevantHistory: '',
        bookedANC: 'No',
        gestationalAgeBooking: '',
        normalDelivery: 'No',
        specificDeliveryDetails: 'Emergency C-section',
        neonatalProblems: 'None',
        congenitalAnomalies: 'None',
        childhoodVaccines: 'Complete',
        otherVaccines: 'Pneumonia',
        nutritionalAssessment: 'Overweight',
        developmentalAssessment: 'Normal',
        regressionMilestones: 'None',
        childInSchool: 'No',
        className: '',
        performanceSatisfactory: '',
        pastIllnessesDrugHistory: 'Amlodipine',
        interventionsCurrentIllness: 'Oxygen, ECG',
        patentMedicineVendors: 'No',
        traditionalHealer: 'No',
        hospitalTreatment: 'Admitted',
        previousTreatmentDetails: 'Amlodipine',
        radiationExposure: 'X-ray',
        otherExposures: 'None',
        headCircumference: 56,
        spo2: 95,
        temperature: 38,
        heartRate: 90,
        respiratoryRate: 22,
        bloodPressure: '140/90',
        enlargedLymphNodes: 'Yes',
        status: 'admitted',
    },
    4: {
        id: 4,
        fullName: 'Bob Williams',
        hospitalNumber: '13579',
        gender: 'male',
        dateOfAdmission: '2024-07-21',
        address: '246 Elm St',
        nextOfKin: 'Mary Williams',
        weight: 90,
        height: 185,
        medicalHistory: 'High cholesterol',
        presentingComplaints: 'Dizziness, headache',
        systemicReview: 'Normal',
        familyHistory: 'High cholesterol',
        additionalRelevantHistory: '',
        bookedANC: 'No',
        gestationalAgeBooking: '',
        normalDelivery: 'No',
        specificDeliveryDetails: 'Forceps delivery',
        neonatalProblems: 'None',
        congenitalAnomalies: 'None',
        childhoodVaccines: 'Complete',
        otherVaccines: 'Flu',
        nutritionalAssessment: 'Needs improvement',
        developmentalAssessment: 'Normal',
        regressionMilestones: 'None',
        childInSchool: 'Yes',
        className: 'Grade 6',
        performanceSatisfactory: 'Yes',
        pastIllnessesDrugHistory: 'Atorvastatin',
        interventionsCurrentIllness: 'Pain relief',
        patentMedicineVendors: 'No',
        traditionalHealer: 'No',
        hospitalTreatment: 'Admitted',
        previousTreatmentDetails: 'Atorvastatin',
        radiationExposure: 'None',
        otherExposures: 'None',
        headCircumference: 57,
        spo2: 97,
        temperature: 37.7,
        heartRate: 85,
        respiratoryRate: 20,
        bloodPressure: '130/85',
        enlargedLymphNodes: 'No',
        status: 'admitted',
    },
    5: {
        id: 5,
        fullName: 'Sarah Brown',
        hospitalNumber: '86420',
        gender: 'female',
        dateOfAdmission: '2024-07-18',
        address: '987 Oak Ave',
        nextOfKin: 'David Brown',
        weight: 55,
        height: 155,
        medicalHistory: 'Migraines',
        presentingComplaints: 'Headache, nausea',
        systemicReview: 'Neurological issues',
        familyHistory: 'Migraines',
        additionalRelevantHistory: '',
        bookedANC: 'Yes',
        gestationalAgeBooking: '8 weeks',
        normalDelivery: 'Yes',
        specificDeliveryDetails: 'Normal',
        neonatalProblems: 'None',
        congenitalAnomalies: 'None',
        childhoodVaccines: 'Complete',
        otherVaccines: 'Flu',
        nutritionalAssessment: 'Good',
        developmentalAssessment: 'Normal',
        regressionMilestones: 'None',
        childInSchool: 'Yes',
        className: 'Grade 2',
        performanceSatisfactory: 'Yes',
        pastIllnessesDrugHistory: 'Ibuprofen',
        interventionsCurrentIllness: 'Pain relief',
        patentMedicineVendors: 'No',
        traditionalHealer: 'No',
        hospitalTreatment: 'Admitted',
        previousTreatmentDetails: 'Ibuprofen',
        radiationExposure: 'None',
        otherExposures: 'None',
        headCircumference: 53,
        spo2: 100,
        temperature: 37,
        heartRate: 70,
        respiratoryRate: 14,
        bloodPressure: '100/60',
        enlargedLymphNodes: 'No',
        status: 'discharged',
    },
};

export default mockPatientData;
